# Generated by Django 3.0.8 on 2020-07-07 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='head_image',
            field=models.ImageField(default='/static/picture/logo.svg', upload_to='head_image', verbose_name='用户头像'),
        ),
    ]
