# Generated by Django 3.0.8 on 2020-07-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20200707_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='head_image',
            field=models.ImageField(upload_to='head_image', verbose_name='用户头像(≤512x512)'),
        ),
    ]
