# Generated by Django 3.0.8 on 2020-07-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_auto_20200707_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='music',
            field=models.CharField(default='5086649776', max_length=20, verbose_name='网易云歌单 ID'),
        ),
    ]
