# Generated by Django 3.0.8 on 2020-07-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_homepage_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='live2d',
            field=models.CharField(choices=[('o', '打开'), ('c', '关闭')], default='c', max_length=1, verbose_name='live2d开启'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='sakura',
            field=models.CharField(choices=[('o', '打开'), ('c', '关闭')], default='c', max_length=1, verbose_name='樱花下落开启'),
        ),
    ]
