# Generated by Django 3.0.8 on 2020-07-09 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_auto_20200709_1844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='sakura',
        ),
    ]
