# Generated by Django 3.0.8 on 2020-07-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_remove_homepage_sakura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='music',
            field=models.CharField(default='28692687', max_length=20, verbose_name='网易云歌曲 ID'),
        ),
    ]
