# Generated by Django 3.0.8 on 2020-07-07 13:42

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200707_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=mdeditor.fields.MDTextField(verbose_name='内容'),
        ),
    ]
