# Generated by Django 3.0.8 on 2020-07-08 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200707_2212'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_time'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='img',
        ),
    ]
